version: '3.8'
name: store

services:

  db-store:
    container_name: store-db-store
    image: postgres:latest
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=store
      - POSTGRES_PASSWORD=store
      - POSTGRES_DB=store
    volumes:
      - $VOLUME/postgres/store/data:/var/lib/postgresql/data
    restart: always
    networks:
      - private-network

  discovery:
    build:
      context: ../polite-transaction-store-discovery/
      dockerfile: Dockerfile
    container_name: store-discovery
    image: store-discovery:latest
    ports:
      - 8761:8761
    environment:
      - spring.datasource.url=jdbc:postgresql://store-db-store:5432/store
      - spring.datasource.username=store
      - spring.datasource.password=store
    restart: always
    networks:
      - private-network

  account:
    build:
      context: ../polite-transaction-account-resource/
      dockerfile: Dockerfile
    container_name: store-account
    image: store-account:latest
    ports:
      - 8080:8080
    environment:
      - spring.datasource.url=jdbc:postgresql://store-db-store:5432/store
      - spring.datasource.username=store
      - spring.datasource.password=store
      - eureka.client.service-url.defaultZone=http://store-discovery:8761/eureka
    deploy:
      mode: replicated
      replicas: 1
    restart: always
    networks:
      - private-network
    depends_on:
      - db-store
      - discovery

  auth:
    build:
      context: ../polite-transaction-auth-resource/
      dockerfile: Dockerfile
    container_name: store-auth
    image: store-auth:latest
    ports:
      - 8081:8080
    environment:
      - eureka.client.service-url.defaultZone=http://store-discovery:8761/eureka
    deploy:
      mode: replicated
      replicas: 1
    restart: always
    networks:
      - private-network
    depends_on:
      - discovery
      - account

networks:
  private-network:
    driver: bridge